stages:
    - test

postman_tests:
    stage: test
    image: 
        name: postman/newman:alpine
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-html
        - newman run collection.json --reporters cli,html --reporter-html-export report.html
    artifacts:
        untracked: false
        expire_in: 30 days
        paths:
            - "report.html"