stages:
    - test

postman_tests:
    stage: test
    image: 
        name: postman/newman:alpine
        entrypoint: [""]
    script:
        - newman --version
        - newman run collection.json
